spring.application.name=SprintW1

# PostgreSQL Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/sprint1_db
spring.datasource.username=postgres
spring.datasource.password=intren13

# JPA Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

server.error.include-stacktrace=never
server.error.include-message=always
server.error.include-binding-errors=always

# File Upload
file.upload-dir=uploads

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET:CHANGE_THIS_default_only_for_local_dev_min_32_chars_long}
jwt.expiration-ms=3600000